name: bench
on: [ merge_group ]
jobs:
  benches:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run Benchmarks
        run: cargo +nightly bench -- --output-format bencher | tee bench.txt
      - name: Store Benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Test Benchmark
          tool: 'cargo'
          output-file-path: bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
