name: build-and-test
on: [ pull_request, merge_group ]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: cargo test
