name: build-and-test
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build
      - name: test
        run: cargo test
